# lammps input file for polymer simulation with dilute ions

# VARIABLES
variable        data_name       index   f1_w0.data
variable        restart_name    index   f1_w0_equil.end.restart
variable        settings_name   index   f1.in.settings
variable        log_name        index   f1_w0.log
variable        dt              index   10.0 # timestep
variable        nSteps_relax    index   1000 # number of data steps for the rescaling box
variable        nSteps_reshape  index   200000 # number of data steps for the rescaling box
variable        nSteps_anneal   index   10000000 # number of data steps for the rescaling box
variable        nSteps_equil    index   10000000 # number of data steps for the rescaling box
variable        nSteps_npt      index   5000000 # number of data steps for NPT
variable        nSteps_nvt      index   5000000 # number of data steps for NVT
variable        nSteps_extend   index   0 # number of data steps for the rescaling box
variable        avg_freq        index   100
variable        coords_freq     index   100
variable        thermo_freq     index   100
variable        dump4avg        index   10
variable        vseed           index   49899 
variable        ANNEAL_TEMP     index   300.0 # Temperature to start from in annealing
variable        FINAL_TEMP      index   300.0 # Temperature ramped to during the final anneal
variable        pressure        index   1.0 # Pressure during the simulations

variable        run             index   1
# Change the name of the log output #
log ${log_name}

#===========================================================
# GENERAL PROCEDURES
#===========================================================
units		real	# g/mol, angstroms, fs, kcal/mol, K, atm, charge*angstrom
dimension	3	# 3 dimensional simulation
newton		on	# use Newton's 3rd law
boundary	p p p	# periodic boundary conditions 
atom_style	hybrid full ellipsoid   # molecular + charge
dielectric	  2.5      # dielectric

#===========================================================
# FORCE FIELD DEFINITION
#===========================================================
special_bonds  lj   0.0 1.0 1.0  coul 0.0 0.0 0.0     # NO     1-4 LJ/COUL interactions
pair_style         hybrid/overlay lj/gromacs/coul/gromacs 9.0 12.0 0.0 12.0 gayberne 1.0 1.0 1.0 12.0 # outer_LJ outer_Coul (cutoff values, see LAMMPS Doc)
bond_style         hybrid elsp elel harmonic
angle_style        hybrid cosine/squared
dihedral_style     hybrid opls
#===========================================================
# SETUP SIMULATIONS
#===========================================================

# READ IN COEFFICIENTS/COORDINATES/TOPOLOGY
read_restart ${restart_name}
include ${settings_name}


# SET RUN PARAMETERS
timestep	10.0		# fs
run_style	verlet 		# Velocity-Verlet integrator
neigh_modify every 1 delay 0  # More relaxed rebuild criteria can be used

# SET QUATERNIONS COMPUTE FIX
compute quaternions all property/atom quatw quati quatj quatk

# THERMODYANMIC VARIABLES
variable        my_step equal   step
variable        my_rho  equal   density
variable        my_vol  equal   vol

#===========================================================
# RESHAPE BOX FOR CONSTANT DENSITY NVT 
#===========================================================
fix dynamics all nve/limit 0.01
compute dynamics_temp all temp
fix mom all momentum 100 linear 1 1 1 angular
fix reshape  all deform 1 x final -93.5849983145 93.5849983145 y final -93.5849983145 93.5849983145 z final -93.5849983145 93.5849983145 units box
variable rot_temp equal c_dynamics_temp
compute rot_press all pressure dynamics_temp
variable rot_press equal c_rot_press
fix therm all print ${thermo_freq} "${my_step} ${my_rho} ${my_vol} ${rot_temp} ${rot_press}" file "thermo.reshape.0.avg" screen "no" title "# Step Density Volume Temp Press"

dump reshape all custom ${coords_freq} reshape.0.lammpstrj id mol type x y z c_quaternions[1] c_quaternions[2] c_quaternions[3] c_quaternions[4] 
dump_modify reshape sort  id

run             ${nSteps_reshape}
unfix dynamics
unfix reshape
undump reshape
unfix therm
unfix mom
uncompute rot_press

# WRITE RESTART FILES, CLEANUP, AND EXIT
write_restart   f1_w0_reshape.0.end.restart
write_data   f1_w0_reshape.0.end.data pair ij

