# lammps input file for polymer simulation with dilute ions

# VARIABLES
variable        data_name       index   f1_w5.data
variable        restart_name    index   f1_w5_npt.0.0.end.restart
variable        settings_name   index   f1_w5.in.settings
variable        log_name        index   f1_w5.log
variable        dt              index   10.0 # timestep
variable        nSteps_relax    index   1000 # number of data steps for the rescaling box
variable        nSteps_reshape  index   200000 # number of data steps for the rescaling box
variable        nSteps_anneal   index   10000000 # number of data steps for the rescaling box
variable        nSteps_equil    index   10000000 # number of data steps for the rescaling box
variable        nSteps_npt      index   5000000 # number of data steps for NPT
variable        nSteps_nvt      index   5000000 # number of data steps for NVT
variable        nSteps_extend   index   0 # number of data steps for the rescaling box
variable        avg_freq        index   100
variable        coords_freq     index   100
variable        thermo_freq     index   100
variable        dump4avg        index   10
variable        vseed           index   62988 
variable        ANNEAL_TEMP     index   300.0 # Temperature to start from in annealing
variable        FINAL_TEMP      index   300.0 # Temperature ramped to during the final anneal
variable        pressure        index   1.0 # Pressure during the simulations

variable        run             index   1
# Change the name of the log output #
log ${log_name}

#===========================================================
# GENERAL PROCEDURES
#===========================================================
units		real	# g/mol, angstroms, fs, kcal/mol, K, atm, charge*angstrom
dimension	3	# 3 dimensional simulation
newton		on	# use Newton's 3rd law
boundary	p p p	# periodic boundary conditions 
atom_style	hybrid full ellipsoid   # molecular + charge
dielectric	  2.5      # dielectric

#===========================================================
# FORCE FIELD DEFINITION
#===========================================================
special_bonds  lj   0.0 1.0 1.0  coul 0.0 0.0 0.0     # NO     1-4 LJ/COUL interactions
pair_style         hybrid/overlay lj/gromacs/coul/gromacs 9.0 12.0 0.0 12.0 gayberne 1.0 1.0 1.0 12.0 # outer_LJ outer_Coul (cutoff values, see LAMMPS Doc)
bond_style         hybrid elsp elel harmonic
angle_style        hybrid cosine/squared
dihedral_style     hybrid opls
#===========================================================
# SETUP SIMULATIONS
#===========================================================

# READ IN COEFFICIENTS/COORDINATES/TOPOLOGY
read_restart ${restart_name}
include ${settings_name}


# SET RUN PARAMETERS
timestep	10.0		# fs
run_style	verlet 		# Velocity-Verlet integrator
neigh_modify every 10 delay 0  # More relaxed rebuild criteria can be used

# SET QUATERNIONS COMPUTE FIX
compute quaternions all property/atom quatw quati quatj quatk

# THERMODYANMIC VARIABLES
variable        my_step equal   step
variable        my_rho  equal   density
variable        my_vol  equal   vol

#===========================================================
# RUN NPT
#===========================================================

# UPDATE RUN PARAMETERS AND CREATE FIX
fix mom all momentum 1000 linear 1 1 1 angular # Zero out system linear and angular momentum every ps 
fix equil_npt all npt/asphere temp 300.0 300.0 $(15.0*dt) iso ${pressure} ${pressure} $(150.0*dt) # NPT, nose-hoover 100 timesteps T relaxation

compute_modify equil_npt_temp extra/dof 13750
# CREATE COORDINATE DUMPS FOR EQUIL_NPTIBRIUM
dump equil_npt all custom ${coords_freq} f1_w5_equil_npt.1.0.lammpstrj id mol type x y z c_quaternions[1] c_quaternions[2] c_quaternions[3] c_quaternions[4] 
dump_modify equil_npt sort  id
variable rot_temp equal c_equil_npt_temp
compute rot_press all pressure equil_npt_temp
variable rot_press equal c_rot_press
fix therm all print ${thermo_freq} "${my_step} ${my_rho} ${my_vol} ${rot_temp} ${rot_press}" file "f1_w5_thermo.equil_npt.1.0.avg" screen "no" title "# Step Density Volume Temp Press"

# RUN EQUIL_NPT
run		${nSteps_npt}

unfix mom
unfix equil_npt
unfix therm
undump equil_npt
uncompute rot_press

# WRITE RESTART FILES, CLEANUP, AND EXIT
write_restart   f1_w5_npt.1.0.end.restart
write_data   f1_w5_npt.1.0.end.data pair ij

